version: 2

jobs:

  build:

    working_directory: ~/workspace

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          key: cache-maven

      - restore_cache:
          key: cache-branch-{{ .Branch }}

      - run:
          name: Build app
          command: ./gradlew assemble

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - .gradle
          key: cache-maven

      - save_cache:
          paths:
            - app/build
          key: cache-branch-{{ .Branch }}

      - run:
          name: Run tests
          command: ./gradlew lint test

      - store_artifacts:
          path: app/build/outputs
          destination: outputs

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results